name: Create Release

on:
  push:
    tags:
      - "v*"

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@master

          - name: Install pnpm
            uses: pnpm/action-setup@v3
            with:
              version: 8

          - name: Install Node.js
            uses: actions/setup-node@v4
            with:
              node-version: lts/*
              cache: "pnpm"

          - name: Install dependencies
            shell: bash
            run: pnpm install

          - name: build
            run: pnpm run build

          - name: Setup Docker buildx
            uses: docker/setup-buildx-action@v2

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Extract Docker Metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ghcr.io/mooncellwiki/mw-deploy-bot
              tags: |
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=sha

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
